[tasks.clean-dist]
command = "trunk"
args = ["clean", "--cargo"]

[tasks.clean-release]
command = "trunk"
args = ["clean", "--cargo", "--dist", "release"]

[tasks.run-dev]
dependencies = ["clean-dist"]
command = "trunk"
args = ["serve", "--open", "--config", "Dev.toml"]

[tasks.build-release]
dependencies = ["clean-release"]
command = "trunk"
args = [
    "build",
    "--release",
    "--minify",
    "--config",
    "Release.toml",
    "--dist",
    "release",
    # "--public-url",
    # "/timkoval.github.io/",
]

[tasks.cp-extra]
script = ["cp -r public/extra/* release/"]

[tasks.run-release]
dependencies = ["build-release", "cp-extra"]

[tasks.update-pages]
command = "git"
args = ["subtree", "push", "--prefix", "release", "origin", "gh-pages"]
